baseurl: "/jekyll-blog"
description: "A simple example blog written with jekyll."
title: "Example blog"
icon: "https://icons-for-free.com/iconfiles/png/512/blog+blogger+internet+people+website+icon-1320168257054370871.png"